### PR TITLE
Bump version to v0.26

### PR DESCRIPTION
**Pull request by qinsoon**
This PR bumps the version to v0.26.

### CODE REVIEW

**Comment by wks** [comment]
If we want to change the MSRV policy, we should discuss in a group, with @steveblackburn and @caizixian involved.  From our previous discussion, we acknowledge that MMTk is a research project and may be aggressive with the technology we use. Our lab machine images are updated automatically, so our burden of maintenance is not high.  We should also communicate with our collaborators and see if there are requirements for a less aggressive MSRV policy.

**Comment by qinsoon** [comment]
I removed the changes about the MSRV policy in this PR. But I still suggest we adopt a less aggressive policy.

We currently use N-1. But in practice, we are not aggressively moving the MSRV, as we know sticking to N-1 all the time would bring troubles, and that is not desirable. However, sticking to N-1 is a valid option according to our policy. Using N-4 or something similar would set a more clear expectation for our users and contributors.

**Review by wks — APPROVED** [review]
LGTM

**Comment by qinsoon** [comment]
binding-refs
OPENJDK_BINDING_REPO=qinsoon/mmtk-openjdk
OPENJDK_BINDING_REF=v0.26
JIKESRVM_BINDING_REPO=qinsoon/mmtk-jikesrvm
JIKESRVM_BINDING_REF=v0.26

**Pull request merged**
