### PR TITLE
Fix object logging code

### LINKED ISSUE #412: Generational barrier object logging code correctness
https://github.com/mmtk/mmtk-core/blob/master/src/plan/barriers.rs#L58

`compare_exchange_metadata` does not internally do fetch-compare-store loop. It just simply do an exclusive load and store. So the object logging code is actually incorrect.

We should do something like this https://github.com/mmtk/mmtk-core/blob/master/src/policy/immortalspace.rs#L149-L173.

@wks Not sure if this is related to your bug.

### PR DESCRIPTION
**Pull request by wenyuzhao**
Fixes #412 

Do object logging correctly.

### CODE REVIEW

**Review by qinsoon — APPROVED** [review]
LGTM. Probably let Kunshan take a look and see if this fixes his bug.

**Comment by wenyuzhao** [comment]
openjdk-binding-test

**Comment by qinsoon** [comment]
I haven't merged the Rust version upgrade PRs for the bindings. The tests will fail for now. I am waiting for the OpenJDK binding to pass the tests before I can merge.

**Comment by caizixian** [comment]
@qinsoon all tests have passed. Is this PR ready for merging?

**Pull request merged**
