### PR TITLE
Upgrade to Rust nightly-2021-08-10

### PR DESCRIPTION
**Pull request by qinsoon**
Related PRs:
* https://github.com/mmtk/mmtk-openjdk/pull/101
* https://github.com/mmtk/mmtk-jikesrvm/pull/83
* https://github.com/mmtk/mmtk-v8/pull/38

### CODE REVIEW

**Comment by qinsoon** [comment]
openjdk-binding-test
OPENJDK_BINDING_REF=rust-nightly-2021-08-10

**Comment by qinsoon** [comment]
v8-binding-test
V8_BINDING_REF=rust-nightly-2021-08-10

**Comment by qinsoon** [comment]
jikesrvm-perf-compare
JIKESRVM_BINDING_BRANCH_REF=rust-nightly-2021-08-10

**Comment by qinsoon** [comment]
openjdk-microbm
OPENJDK_BINDING_BRANCH_REF=rust-nightly-2021-08-10

**Review by wenyuzhao — APPROVED** [review]
LGTM

**Pull request merged**
