### PR TITLE
Object model cleanup

### PR DESCRIPTION
**Pull request by javadamiri**
This PR addresses issue #171 on object metadata cleanup.

### CODE REVIEW

**Comment by javadamiri** [comment]
jikesrvm-binding-test
JIKESRVM_BINDING_REF=object_model_cleanup

**Comment by javadamiri** [comment]
openjdk-binding-test
OPENJDK_BINDING_REVISION=object_model_cleanup

**Comment by javadamiri** [comment]
openjdk-perf-compare
OPENJDK_BINDING_BRANCH_REF=object_model_cleanup

**Comment by javadamiri** [comment]
jikesrvm-perf-compare
JIKESRVM_BINDING_BRANCH_REF=object_model_cleanup

**Comment by javadamiri** [comment]
v8-binding-test
V8_BINDING_REVISION=object_model_cleanup

**Review by qinsoon — APPROVED** [review]
Looks good to me. Nice comments for the code. 

This PR does not fully addresses #171, but one step towards #171. `get_relative_offset()` is still confusing, and introduced subtle assumptions between 'available_bits' and `GC_BYTE_OFFSET`. In future PRs, we should see this part gets cleaner.

**Pull request merged**
