### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by qinsoon**
This PR adds a contributing seciton to README. Before we have more detailed documentation for contributing and developing, this serves as a simple guide line for contributors.

### CODE REVIEW

**Comment by wks** [comment]
LGTM now.

**Review by wks — APPROVED** [review]
LGTM

**Review by caizixian — CHANGES_REQUESTED** [review]
We should consider using the GitHub contribution guide feature https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by qinsoon** [comment]
> We should consider using the GitHub contribution guide feature https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

I have created a `CONTRIBUTING.md` as the github doc suggests. Can you please take a look again? @caizixian

**Review by caizixian — APPROVED** [review]

**Pull request merged**
