### PR TITLE
Cancel CI runs if PRs get updated

### LINKED ISSUE #728: Cancel CI runs if PRs get updated
We should add the following to every CI in order to cancel a run for a PR if a new commit occurs. Better if we don't waste compute cycles for nothing.

```yaml
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```

### PR DESCRIPTION
**Pull request by k-sareen**
Closes #728.

### CODE REVIEW

**Comment by qinsoon** [comment]
I think you would need the group name to be a combination of head ref and job name. Otherwise only all the workflows and all the jobs share one group, and only one can run.

**Comment by k-sareen** [comment]
Yeah I see. Since we have multiple workflows/CIs it's more complex. Something like this maybe:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```

**Comment by qinsoon** [comment]
> Yeah I see. Since we have multiple workflows/CIs it's more complex. Something like this maybe:
> 
> ```yaml
> concurrency:
>   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
>   cancel-in-progress: true
> ```

I think you need the job name or ID in the group name as well. One file is one workflow, but it can include multiple jobs. You still want all the jobs in one workflow to run.

**Comment by k-sareen** [comment]
> > Yeah I see. Since we have multiple workflows/CIs it's more complex. Something like this maybe:
> > ```yaml
> > concurrency:
> >   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
> >   cancel-in-progress: true
> > ```
> 
> I think you need the job name or ID in the group name as well. One file is one workflow, but it can include multiple jobs. You still want all the jobs in one workflow to run.

It seems to be working right now? I'll add a dummy change to see if it's canceling as expected.

**Comment by qinsoon** [comment]
If it runs, that's fine. I was just guessing based on their document.

**Comment by k-sareen** [comment]
Cool! Seems like runs actually get canceled if you update the PR.

**Review by qinsoon — APPROVED** [review]
LGTM

**Pull request merged**
