### PR TITLE
API Cleanup

### PR DESCRIPTION
**Pull request by qinsoon**
This PR fixes a few issues in our current API.

* Does some cleanups in https://github.com/mmtk/mmtk-core/issues/59.
  * Clarifies `tls` in the `enable_collection()` call.
  * Removes `type_refer` from the `post_alloc()` call.
  * Removes `scan_region()` from our API which is not used by any binding.
* Removes deprecated methods from our traits:
  * `collector_count()` in `ActivePlan`
  * `reset_thread_counter()` in `Scanning`
* Makes the type of `worker` in `start_worker()` and `spawn_worker_thread()` match (https://github.com/mmtk/mmtk-core/issues/112).
* Fixes unclear `unsafe` keywords in the `ActivePlan` trait (https://github.com/mmtk/mmtk-core/issues/141).

This PR closes https://github.com/mmtk/mmtk-core/issues/112, closes https://github.com/mmtk/mmtk-core/issues/141.

### CODE REVIEW

**Comment by qinsoon** [comment]
v8-binding-test
V8_BINDING_REF=api-cleanup

**Comment by qinsoon** [comment]
jikesrvm-binding-test
JIKESRVM_BINDING_REF=api-cleanup

**Comment by qinsoon** [comment]
openjdk-binding-test
OPENJDK_BINDING_REF=api-cleanup

**Review by javadamiri — APPROVED** [review]
LGTM

**Pull request merged**
