### PR TITLE
Check bounds of active chunk metadata spec in is_chunk_mapped

### LINKED ISSUE #383: is_meta_space_mapped in MallocSpace may return true for non-marksweep plans
I encountered this bug when I was debugging GenCopy. What happened was that for an object that is not in any of our heap spaces, the check https://github.com/mmtk/mmtk-core/blob/f1b3ce4cf67149f724430406eea49f7a3b4c7fb2/src/policy/space.rs#L238-L250
will check whether the object is allocated by malloc.  `is_alloced_by_malloc` should return false if the object is not allocated by malloc. 
https://github.com/mmtk/mmtk-core/blob/f1b3ce4cf67149f724430406eea49f7a3b4c7fb2/src/policy/mallocspace/metadata.rs#L158-L160

However, `is_meta_space_mapped()` may incorrectly return true that indicates the chunk where the object resides is allocated by malloc, and then when we check whether there is an alloc bit for the object, another assertion in side metadata load may fail due to the the alloc bit metadata is not mapped at all. This results in a panic in debug builds. 

We expect `is_alloced_by_malloc` returns false instead of panicking.

To reproduce
---

I have pushed a branch that can reproduce this bug: https://github.com/mmtk/mmtk-core/tree/bug-is_alloced_by_malloc.
Build `slowdebug` with https://github.com/mmtk/mmtk-openjdk/commit/fd3bd974bfdb99543efd185ee29f15de17f145b7.
Run (you may need to run it several times to reproduce the bug): 
```
RUST_BACKTRACE=1 MMTK_PLAN=GenCopy build/linux-x86_64-normal-server-slowdebug/jdk/bin/java -XX:+UseThirdPartyHeap -server -XX:MetaspaceSize=100M -Xms500M -Xmx500M -jar /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar hsqldb
```
Panic
```
thread '<unnamed>' panicked at '0x17fd13e3f000 of size 4096 is not mapped', /home/yilin/Code/mmtk-core/src/util/memory.rs:121:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/5c029265465301fe9cb3960ce2a5da6c99b8dcf2/library/std/src/panicking.rs:435:5
   2: mmtk::util::memory::panic_if_unmapped
             at /home/yilin/Code/mmtk-core/src/util/memory.rs:121:18
   3: mmtk::util::metadata::side_metadata::global::ensure_metadata_is_mapped
             at /home/yilin/Code/mmtk-core/src/util/metadata/side_metadata/global.rs:216:5
   4: mmtk::util::metadata::side_metadata::global::load_atomic
             at /home/yilin/Code/mmtk-core/src/util/metadata/side_metadata/global.rs:226:9
   5: mmtk::policy::mallocspace::metadata::is_alloced_object
             at /home/yilin/Code/mmtk-core/src/policy/mallocspace/metadata.rs:167:5
   6: mmtk::policy::mallocspace::metadata::is_alloced
             at /home/yilin/Code/mmtk-core/src/policy/mallocspace/metadata.rs:163:5
   7: mmtk::policy::mallocspace::metadata::is_alloced_by_malloc
             at /home/yilin/Code/mmtk-core/src/policy/mallocspace/metadata.rs:159:50
   8: mmtk::policy::space::SFTMap::is_in_space
             at /home/yilin/Code/mmtk-core/src/policy/space.rs:246:13
   9: mmtk::util::address::ObjectReference::is_mapped
             at /home/yilin/Code/mmtk-core/src/util/address.rs:503:9
  10: mmtk::memory_manager::is_mapped_object
             at /home/yilin/Code/mmtk-core/src/memory_manager.rs:268:5
  11: is_mapped_object
             at /home/yilin/Code/mmtk-openjdk/mmtk/src/api.rs:159:5
  12: _ZNK8MMTkHeap5is_inEPKv
  13: _ZNK8MMTkHeap14is_in_reservedEPKv
  14: _ZNK13CollectedHeap6is_oopEP7oopDesc
  15: _ZN7oopDesc6is_oopEPS_b
  16: _ZN10HandleArea15allocate_handleEP7oopDesc
  17: _ZN6HandleC1EP6ThreadP7oopDesc
  18: _ZN10JavaThread7prepareEP8_jobject14ThreadPriority
  19: JVM_StartThread
  20: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by k-sareen**
Closes #383. The issue in #383 stemmed from `address_to_meta_address()` returning a metadata address outside of the range of the `ACTIVE_CHUNK_METADATA_SPEC` since the function simply translates a data address to a metadata address without checking if it is crossing any metadata bounds.

### CODE REVIEW

**Comment by k-sareen** [comment]
The offset being its own type makes the compilation error -- should I implement `+` on the offset?

**Comment by qinsoon** [comment]
> The offset being its own type makes the compilation error -- should I implement `+` on the offset?

No. You can get the offset from the spec as `Address` or `usize`.

**Comment by k-sareen** [comment]
Yes I missed the function -- done.

**Review by qinsoon — APPROVED** [review]
LGTM

**Pull request merged**
